//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vet_Clinic_AIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int ID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Description { get; set; }
        public int PatientID { get; set; }
        public Nullable<int> ProceduresID { get; set; }
        public int Cost { get; set; }
        public string StatusPayment { get; set; }
        public int ClientsID { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual Procedur Procedur { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
