//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vet_Clinic_AIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentsClients
    {
        public int ID { get; set; }
        public int AppointmentsID { get; set; }
        public int ClientsID { get; set; }
    }
}
